export const CHAT_CONTEXT_WINDOW_SIZE = 8;
export const CHAT_SUMMARY_BUFFER_SIZE = 2;
export const CHAT_SUMMARY_TRIGGER_INTERVAL =
  CHAT_CONTEXT_WINDOW_SIZE - CHAT_SUMMARY_BUFFER_SIZE;
export const CHAT_SUMMARY_INITIAL_MESSAGE_LIMIT =
  CHAT_SUMMARY_TRIGGER_INTERVAL;
export const CHAT_SUMMARY_MESSAGE_LIMIT = CHAT_CONTEXT_WINDOW_SIZE;
